homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    # dilanjutkan ...
]

projectone/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def profile(request):
    return render(request, 'profile.html')

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Projectone</title>
    </head>
    <style>
    body{
        background-image: url('/static/bg1.jpg');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }
    </style>
    <body>
        <h1 style="color:white">My Website</h1>
        <a href="{% url 'homepage:profile' %}" style="color:white">Profile</a>
        <p style="color:white">ini cuma untuk coba-coba mengulang pelajaran PPW</p>
        <img src="{% static 'tanda tangan.png' %}" width="104" height="142">
    </body>
</html>

homepage/templates/profile.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Projectone</title>
    </head>
    <style>
        body{
            background-image: url('/static/bg1.jpg');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
        }
    </style>
    <body>
        <h1 style="color:white">My Profile</h1>
        <a href="{% url 'homepage:index' %}" style="color:white">Home</a>
        <p style="color:white">blum ada isinya gan</p>
        <img src="{% static 'tanda tangan.png' %}" width="104" height="142">
    </body>
</html>